name: Setup
description: Setup environment for building and deploying the project
runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 20
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Rspack persistent cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: node_modules/.cache/rspack
        key: rspack-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          rspack-
