project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /i18n/en/code.json
    translation: /i18n/%two_letters_code%/code.json
    dest: /website/code.json
    languages_mapping: &languages_mapping
      two_letters_code:
        pt-BR: pt-BR
        zh-CN: zh-CN
        zh-TW: zh-TW

  - source: /i18n/en/docusaurus-theme-classic/*.json
    translation: /i18n/%two_letters_code%/docusaurus-theme-classic/%original_file_name%
    dest: /website/theme-classic/%original_file_name%
    languages_mapping: *languages_mapping

  - source: /docs/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/%original_file_name%
    dest: /website/docs/%original_file_name%
    languages_mapping: *languages_mapping

  - source: /src/pages/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/%original_file_name%
    dest: /website/pages/%original_file_name%
    languages_mapping: *languages_mapping
