allowBuilds:
  "@biomejs/biome": true
  "@swc/core": true
  core-js: false
  core-js-pure: false
  lefthook: true

blockExoticSubdeps: true

minimumReleaseAge: 4320 # 3 days

minimumReleaseAgeExclude:
  # Renovate security update: js-yaml@4.2.0
  - js-yaml@4.2.0

overrides:
  serialize-javascript@<=7.0.2: ^7.0.3
  serialize-javascript@>=5.0.0 <7.0.5: ^7.0.5
  uuid@<11.1.1: 14.0.1

trustPolicy: no-downgrade

trustPolicyExclude:
  - detect-port@1.6.1
  - semver@6.3.1
