allowBuilds:
  "@biomejs/biome": true
  "@swc/core": true
  core-js: false
  core-js-pure: false
  lefthook: true

minimumReleaseAge: 1440 # 1 day

trustPolicy: no-downgrade

blockExoticSubdeps: true
