import { writeFile } from "node:fs/promises";

import { dump } from "js-yaml";

import { languages } from "./languages.ts";

const languagesMapping = {
  two_letters_code: Object.fromEntries(
    languages.map(({ crowdin, docusaurus }) => [crowdin, docusaurus]),
  ),
};

const config = {
  project_id_env: "CROWDIN_PROJECT_ID",
  api_token_env: "CROWDIN_PERSONAL_TOKEN",
  preserve_hierarchy: true,
  files: [
    {
      source: "/i18n/en/code.json",
      translation: "/i18n/%two_letters_code%/code.json",
      dest: "/website/code.json",
      languages_mapping: languagesMapping,
    },
    {
      source: "/i18n/en/docusaurus-theme-classic/*.json",
      translation:
        "/i18n/%two_letters_code%/docusaurus-theme-classic/%original_file_name%",
      dest: "/website/theme-classic/%original_file_name%",
      languages_mapping: languagesMapping,
    },
    {
      source: "/docs/*.md",
      translation:
        "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/%original_file_name%",
      dest: "/website/docs/%original_file_name%",
      languages_mapping: languagesMapping,
    },
    {
      source: "/src/pages/*.md",
      translation:
        "/i18n/%two_letters_code%/docusaurus-plugin-content-pages/%original_file_name%",
      dest: "/website/pages/%original_file_name%",
      languages_mapping: languagesMapping,
    },
    {
      source: "/src/pages/*.mdx",
      translation:
        "/i18n/%two_letters_code%/docusaurus-plugin-content-pages/%original_file_name%",
      dest: "/website/pages/%original_file_name%",
      languages_mapping: languagesMapping,
    },
  ],
};

await writeFile(
  "crowdin.yml",
  `# Generated by scripts/generate-crowdin-config.ts from languages.yml. Do not edit directly.
${dump(config, { noRefs: true })}`,
);
