#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"

# Validate languages.yml: every entry needs a string label and, if present, a string crowdin.
invalid="$(yq 'to_entries | map(select((.value.label | type) != "!!str" or ((.value.crowdin // "") | type) != "!!str")) | .[].key' "$root/languages.yml")"
if [[ -n "$invalid" ]]; then
  echo "languages.yml: invalid entries (label is required, crowdin must be a string): ${invalid//$'\n'/ }" >&2
  exit 1
fi

header="# Generated by scripts/generate.sh from languages.yml. Do not edit directly."

# Generate languages.yaml: English plus the translations in file order, each pointing its edit link to Crowdin.
{
  echo "$header"
  yq '
    {"en": {"locale": "en", "label": "English", "weight": 1}}
    + (to_entries | .[] as $l ireduce ({}; . + {$l.key: {"locale": $l.key, "label": $l.value.label, "weight": (length + 2), "cascade": {"params": {"editURL": ("https://crowdin.com/project/ublacklist/" + ($l.value.crowdin // $l.key))}}}}))
  ' "$root/languages.yml"
} > "$root/config/_default/languages.yaml"

# Generate module.yaml: mount content/<tag> per language, with content/en as the fallback for translations.
{
  echo "$header"
  yq '
    {"mounts": (
      [{"source": "content/en", "target": "content", "sites": {"matrix": {"languages": ["en"]}}}]
      + (keys | map({"source": "content/" + ., "target": "content", "sites": {"matrix": {"languages": [downcase]}}}))
      + [{"source": "content/en", "target": "content", "sites": {"matrix": {"languages": (keys | map(downcase))}}}]
    )}
  ' "$root/languages.yml"
} > "$root/config/_default/module.yaml"

# Generate crowdin.yml: map Crowdin language codes to local <tag> directories.
{
  echo "$header"
  yq '
    (to_entries | .[] as $l ireduce ({}; . + {($l.value.crowdin // $l.key): $l.key})) as $mapping
    | {
      "project_id_env": "CROWDIN_PROJECT_ID",
      "api_token_env": "CROWDIN_PERSONAL_TOKEN",
      "preserve_hierarchy": true,
      "files": (
        [
          {"source": "/i18n/en.json", "translation": "/i18n/%two_letters_code%.json", "dest": "/website/i18n.json"},
          {"source": "/content/en/*.md", "ignore": ["/content/en/_index.md"], "translation": "/content/%two_letters_code%/%original_file_name%", "dest": "/website/content/%original_file_name%"},
          {"source": "/content/en/docs/*.md", "translation": "/content/%two_letters_code%/docs/%original_file_name%", "dest": "/website/content/docs/%original_file_name%"},
          {"source": "/content/en/rulesets/*.md", "translation": "/content/%two_letters_code%/rulesets/%original_file_name%", "dest": "/website/content/rulesets/%original_file_name%"}
        ]
        | map(. + {"languages_mapping": {"two_letters_code": $mapping}})
      )
    }
  ' "$root/languages.yml"
} > "$root/crowdin.yml"
