#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"

header="# Generated by scripts/generate.sh from languages.yml. Do not edit directly."

{
  echo "$header"
  yq '
    {"en": {"locale": "en", "label": "English", "weight": 1}}
    + (to_entries | .[] as $l ireduce ({}; . + {$l.key: {"locale": $l.key, "label": $l.value.label, "weight": (length + 2)}}))
  ' "$root/languages.yml"
} > "$root/config/_default/languages.yaml"

{
  echo "$header"
  yq '
    {"mounts": (
      [{"source": "content/en", "target": "content", "sites": {"matrix": {"languages": ["en"]}}}]
      + (keys | map({"source": "content/" + ., "target": "content", "sites": {"matrix": {"languages": [downcase]}}}))
      + [{"source": "content/en", "target": "content", "sites": {"matrix": {"languages": (keys | map(downcase))}}}]
    )}
  ' "$root/languages.yml"
} > "$root/config/_default/module.yaml"

{
  echo "$header"
  yq '
    (to_entries | .[] as $l ireduce ({}; . + {($l.value.crowdin // $l.key): $l.key})) as $mapping
    | {
      "project_id_env": "CROWDIN_PROJECT_ID",
      "api_token_env": "CROWDIN_PERSONAL_TOKEN",
      "preserve_hierarchy": true,
      "files": (
        [
          {"source": "/i18n/en.yaml", "translation": "/i18n/%two_letters_code%.yaml", "dest": "/website/i18n.yaml"},
          {"source": "/content/en/docs/*.md", "translation": "/content/%two_letters_code%/docs/%original_file_name%", "dest": "/website/docs/%original_file_name%"},
          {"source": "/content/en/privacy-policy.md", "translation": "/content/%two_letters_code%/%original_file_name%", "dest": "/website/pages/%original_file_name%"},
          {"source": "/content/en/rulesets/*.md", "translation": "/content/%two_letters_code%/rulesets/%original_file_name%", "dest": "/website/pages/rulesets/%original_file_name%"}
        ]
        | map(. + {"languages_mapping": {"two_letters_code": $mapping}})
      )
    }
  ' "$root/languages.yml"
} > "$root/crowdin.yml"
