name: Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: true
          cache: true

      - name: Restore rspack cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: node_modules/.cache/rspack
          key: ${{ runner.os }}-rspack-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-rspack-

      - name: Check by Biome
        run: pnpm biome ci --reporter=github

      - name: Check by Prettier
        run: pnpm prettier --check '**/*.{md,mdx,yaml,yml}'

      - name: Check by TypeScript
        run: pnpm tsgo

      - name: Build
        run: pnpm build --locale=en
