name: Check
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
permissions: {}
defaults:
  run:
    shell: bash
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        run: pnpm run ci

      - name: Build
        run: pnpm build
