name: Format

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Format by Biome
        run: pnpm biome format --write

      - name: Format by Prettier
        run: pnpm prettier --write '**/*.{md,mdx,yaml,yml}'

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add .
            git commit -m "format by biome and prettier [skip ci]"
            git push
          fi
