name: Format and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Format by Biome
        run: pnpm biome format --write

      - name: Format by Prettier
        run: pnpm prettier --write '**/*.{md,yaml,yml}'

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add .
            git commit -m "format by biome and prettier [skip ci]"
            git push
          fi

  build:
    needs: format

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Crowdin
        uses: crowdin/github-action@9787f4fcb6a8450929673f1e8db841e8a5c35a2f # v2.10.0
        with:
          download_translations: true
          export_only_approved: true
          download_translations_args: --ignore-match
            --language=ja
          push_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Build
        run: pnpm build

      - name: Upload
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: build/

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
